my:
  header: Employee Registration Page!
  

spring:
  h2:
    console:
      enabled: true
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp
  datasource:
    url: 
    username: 
    password:
    
 


